kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast
  namespace: develop
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: us-east-2a, us-east-2b, us-east-2c
  fsType: ext4